[custom]

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🚀 国家选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 国家选择,https://raw.githubusercontent.com/WC-Dream/ACL4SSR/WD/Clash/proxy.list
ruleset=🚀 国家选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 国家选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 国家选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/WC-Dream/ACL4SSR/WD/Clash/direct.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 国家选择`select`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇸🇬 狮城自动`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇮🇳 印度自动`[]🇬🇧 英国自动`[]🇫🇷 法国自动`[]🇩🇪 德国自动`[]🇳🇱 荷兰自动`[]🇸🇪 瑞典自动`[]🇫🇮 芬兰自动`[]🇵🇱 波兰自动`[]🇷🇺 俄罗斯自动`[]🇨🇭 瑞士自动`[]🇱🇻 拉脱维亚自动`[]🇨🇦 加拿大自动

custom_proxy_group=🇸🇬 狮城自动`url-test`(新加坡|狮城|Singapore|SINGAPORE|SG[-_ ]|🇸🇬)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇭🇰 香港自动`url-test`(香港|Hong Kong|Hongkong|HONG KONG|HK[-_ ]|🇭🇰)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇹🇼 台湾自动`url-test`(台湾|Taiwan|TAIWAN|TW[-_ ]|🇹🇼)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇺🇸 美国自动`url-test`(美国|United States|UnitedStates|USA|US[-_ ]|America|AMERICA|🇺🇸)`http://www.gstatic.com/generate_204`300,,250

custom_proxy_group=🇯🇵 日本自动`url-test`(日本|Japan|JAPAN|JP[-_ ]|Tokyo|TOKYO|东京|大阪|🇯🇵)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇰🇷 韩国自动`url-test`(韩国|Korea|KOREA|South Korea|SouthKorea|KOR|KR[-_ ]|首尔|Seoul|🇰🇷)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇮🇳 印度自动`url-test`(印度|India|INDIA|IN[-_ ]|🇮🇳)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇬🇧 英国自动`url-test`(英国|UK|United Kingdom|UnitedKingdom|Britain|England|GB[-_ ]|🇬🇧)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇫🇷 法国自动`url-test`(法国|France|FRANCE|FR[-_ ]|Paris|巴黎|🇫🇷)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇩🇪 德国自动`url-test`(德国|Germany|GERMANY|DE[-_ ]|Frankfurt|法兰克福|🇩🇪)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇳🇱 荷兰自动`url-test`(荷兰|Netherlands|NETHERLANDS|NL[-_ ]|Amsterdam|阿姆斯特丹|🇳🇱)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇸🇪 瑞典自动`url-test`(瑞典|Sweden|SWEDEN|SE[-_ ]|Stockholm|斯德哥尔摩|🇸🇪)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇫🇮 芬兰自动`url-test`(芬兰|Finland|FINLAND|FI[-_ ]|Helsinki|赫尔辛基|🇫🇮)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇵🇱 波兰自动`url-test`(波兰|Poland|POLAND|PL[-_ ]|Warsaw|华沙|🇵🇱)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇷🇺 俄罗斯自动`url-test`(俄罗斯|Russia|RUSSIA|Russian|RU[-_ ]|Moscow|莫斯科|🇷🇺)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇨🇭 瑞士自动`url-test`(瑞士|Switzerland|SWITZERLAND|Swiss|CH[-_ ]|Zurich|苏黎世|🇨🇭)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇱🇻 拉脱维亚自动`url-test`(拉脱维亚|Latvia|LATVIA|LV[-_ ]|Riga|里加|🇱🇻)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🇨🇦 加拿大自动`url-test`(加拿大|Canada|CANADA|CA[-_ ]|Toronto|多伦多|Vancouver|温哥华|🇨🇦)`http://www.gstatic.com/generate_204`300,,150

custom_proxy_group=🚀 手动切换`select`.*

custom_proxy_group=♻️ 自动选择`url-test`.*`https://cp.cloudflare.com/generate_204`300,,200

custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 国家选择`[]🚀 手动切换

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 国家选择`[]🚀 手动切换`[]DIRECT`[]🇸🇬 狮城自动`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🇮🇳 印度自动`[]🇬🇧 英国自动`[]🇫🇷 法国自动`[]🇩🇪 德国自动`[]🇳🇱 荷兰自动`[]🇸🇪 瑞典自动`[]🇫🇮 芬兰自动`[]🇵🇱 波兰自动`[]🇷🇺 俄罗斯自动`[]🇨🇭 瑞士自动`[]🇱🇻 拉脱维亚自动`[]🇨🇦 加拿大自动`].*

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/WC-Dream/ACL4SSR/refs/heads/WD/Clash/GeneralClashConfig.yml

clash_rule_base=https://raw.githubusercontent.com/daolingze/ACL4SSR/refs/heads/WD/Clash/111GeneralClashConfig.yml